# Generated by Django 5.0.3 on 2024-04-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('shop', models.CharField(max_length=256)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
